# **Week - 5 Assignment**

Q1: What are the key limitations of traditional MapReduce that make Spark a preferred choice for modern big data processing?

Problems with Traditional MapReduce
- It writes intermediate results to disk after every processing stage.
- It has a complex programming model and mainly supports batch processing.

Why Spark is preferred
- Spark uses in-memory computing, so it processes data much faster.
- It supports SQL, streaming, and machine learning within a single framework
- It is easier to use and write applications.

Q2: Explain how Spark uses In-Memory Computing to speed up iterative machine learning algorithms compared to disk-based systems.

- Spark stores data in memory (RAM) instead of writing it to disk after every step.
- Machine learning algorithms use the same data many times.
- Since the data is already in memory, Spark does not need to read it from disk again and again.
- This reduces processing time and makes machine learning algorithms much faster than disk-based systems like MapReduce.

## **Note:**
I have used Pandas wherever it was not specifically mentioned to use Spark. Since the Week-5 modules were mostly on Pandas, and it was also mentioned in the Week-5 Doubts Session that we can use either Pandas or Spark for this assignment. Wherever the question specifically asked to write a Spark command, i have used Spark there.

In [0]:
df = spark.table("sales").toPandas()

In [0]:
spark_df = spark.table("sales")

Q3: Write a code snippet to remove all duplicate rows from a DataFrame based on a specific set of columns: user_id and transaction_date.

In [0]:
df1 = df.drop_duplicates(["user_id", "transaction_date"])
df1.head(10)

   transaction_id  user_id  ...     status       raw_timestamp
0             130     1160  ...    Unknown 1982-12-26 19:49:53
1             222     1121  ...    Pending 1993-12-14 00:30:06
2             227     1055  ...  Completed 1988-01-24 20:32:51
3             249     1051  ...  Completed 1973-03-24 00:16:21
4             265     1016  ...    Pending 1981-08-08 11:26:57
5             205     1199  ...    Unknown 2015-01-29 06:36:26
6             151     1016  ...  Completed 2005-06-12 02:07:05
7               8     1088  ...    Pending 1978-09-25 17:31:16
8              33     1074  ...  Completed 2025-01-14 07:10:02
9              45     1094  ...    Pending 2015-02-04 13:41:09

[10 rows x 15 columns]

Q4: Given a DataFrame df_sales, write a query to filter for rows where the region is 'West' and then group by product_category to find the average sale_amount.

In [0]:
df2 = df[df["region"] == "West"].groupby("product_category")["sale_amount"].mean()
print("Mean of each Product Category")
df2

Mean of each Product Category

product_category
Books          2555.329649
Clothing       2587.388333
Electronics    2764.461961
Groceries      2684.731277
Name: sale_amount, dtype: float64

Q5: What is the difference between .na.drop() and .na.fill()? Provide a code example of filling null values in a status column with the string 'Unknown'.
- **.na.drop() removes rows that contain null values.**
- **.na.fill() replaces null values with a specified value.**

In [0]:
df["status"] = df["status"].fillna("Unknown")
df.head()

   transaction_id  user_id  ...     status       raw_timestamp
0             130     1160  ...    Unknown 1982-12-26 19:49:53
1             222     1121  ...    Pending 1993-12-14 00:30:06
2             227     1055  ...  Completed 1988-01-24 20:32:51
3             249     1051  ...  Completed 1973-03-24 00:16:21
4             265     1016  ...    Pending 1981-08-08 11:26:57

[5 rows x 15 columns]

Q6: Write a query to find the total count of records for each city in a DataFrame, but only for cities where the count is greater than 100.

In [0]:
df["city"].value_counts()[df["city"].value_counts() > 100]

city
Chennai      181
Mumbai       163
Delhi        157
Hyderabad    156
Bangalore    143
Name: count, dtype: int64

Q7: How does the immutability of Spark DataFrames affect how you perform "data cleaning" steps like dropping columns or renaming them?

Spark DataFrames are immutable, so they cannot be changed directly.
When we drop or rename columns, Spark creates a new DataFrame instead of modifying the existing one.

Q8: Write a Spark command to filter a dataset for rows where the age is between 18 and 30 (inclusive) and the subscription is 'Premium'.

In [0]:
spark_df.filter((spark_df.age >= 18) & (spark_df.age <= 30) & (spark_df.subscription == "Premium")).show()

+--------------+-------+----------------+---------------+--------------------+---+------------+------+---------+--------+----------------+-----------+-------+---------+-------------------+
|transaction_id|user_id|transaction_date|       username|               email|age|subscription|region|     city|store_id|product_category|sale_amount|  price|   status|      raw_timestamp|
+--------------+-------+----------------+---------------+--------------------+---+------------+------+---------+--------+----------------+-----------+-------+---------+-------------------+
|           205|   1199|      2026-04-04|     torreslori|gfleming@example.net| 22|     Premium|  West|Hyderabad|      10|           Books|    2068.42|1298.06|     NULL|2015-01-29 06:36:26|
|           123|   1045|      2026-01-27|       emiranda| wmiller@example.org| 24|     Premium| North|Hyderabad|      10|           Books|    1269.13|2973.22|  Pending|2010-12-26 22:21:31|
|            62|   1083|      2025-07-02|      johnwhite| apatton@example.com| 30|     Premium|  East|    Delhi|       5|       Groceries|    4002.73| 150.03|Completed|2003-02-22 08:46:58|
|            95|   1143|      2025-08-22|   joshuacarney|denise88@example.org| 22|     Premium| South|Bangalore|      14|       Groceries|    2168.35|1400.21|Completed|1971-12-18 12:13:16|
|            59|   1103|      2025-12-12|     michelle31|gerald49@example.net| 19|     Premium| North|  Chennai|      15|       Groceries|    4267.24|2832.94|Completed|2016-09-04 11:24:09|
|           270|   1076|      2025-12-25|       joseph03|rodneyhunter@exam...| 22|     Premium| South|   Mumbai|      18|           Books|    4771.38|1658.01|     NULL|2001-05-21 18:56:21|
|           207|   1014|      2025-08-11|     kellyadams|  todd18@example.org| 21|     Premium| South|  Chennai|       6|           Books|    1003.24|  93.69|  Pending|2022-09-14 20:39:45|
|           172|   1102|      2026-01-23|     jamieadams| emily13@example.com| 21|     Premium| North|Hyderabad|      13|       Groceries|    3070.32|1813.71|  Pending|1987-04-29 06:34:23|
|            45|   1062|      2025-07-31|      matthew76| izamora@example.net| 19|     Premium|  West|   Mumbai|      19|        Clothing|     244.42|1624.55|  Pending|1985-09-18 17:57:28|
|            41|   1097|      2026-05-14|     stevensjoy|cooperselena@exam...| 28|     Premium|  West|   Mumbai|       2|           Books|     151.79|2145.18|Completed|2017-06-14 02:01:45|
|           102|   1081|      2025-10-18|  salazaraustin|warnermiguel@exam...| 28|     Premium| North|   Mumbai|       4|       Groceries|    2789.97| 987.25|     NULL|1976-11-03 06:41:01|
|            42|   1103|      2025-07-07|    alexandra40|brownwilliam@exam...| 26|     Premium| South|  Chennai|       8|        Clothing|    3844.53| 403.88|Completed|2009-02-21 11:21:47|
|             2|   1111|      2026-05-09|        zwatson| jacob35@example.org| 20|     Premium| North|Hyderabad|      10|     Electronics|    3810.62|1907.23|Completed|2021-12-22 15:55:07|
|           208|   1021|      2026-03-11|petersalexander|ernestsutton@exam...| 28|     Premium|  East|  Chennai|      15|     Electronics|    2902.61| 763.58|  Pending|1999-06-02 18:16:52|
|           282|   1092|      2026-05-02|        nancy81|  adam34@example.org| 29|     Premium| South|Bangalore|       2|           Books|    4244.98|2127.06|Completed|1971-09-05 07:34:46|
|             1|   1151|      2025-11-29|   andrewmathis|charlesweiss@exam...| 22|     Premium| South|   Mumbai|      10|     Electronics|    3322.55|1892.66|  Pending|2021-07-08 22:43:39|
|           154|   1031|      2026-05-01|       xfreeman|urodriguez@exampl...| 22|     Premium| South|Hyderabad|      10|     Electronics|    4031.63|2327.48|     NULL|2002-08-27 00:14:19|
|            92|   1176|      2026-06-22|       fsanchez|johnsonadam@examp...| 20|     Premium|  East|Bangalore|       4|           Books|    3605.28|1419.41|     NULL|2011-09-08 21:04:32|
|            28|   1045|      2025-12-25|     michelle65|hherring@example.net| 29|     Premium|  East|   Mumbai|      10|        Clothing|    1987.27|1729.64|     NULL|1970-03-23 23:40:46|
|           163|   1183|      2025-10-15|     lloydemily|ronaldgonzalez@ex...| 21|     Premium|  West|    Delhi|       7|           Books|      508.6| 138.43|  Pending|1994-10-08 11:13:49|
+--------------+-------+----------------+---------------+--------------------+---+------------+------+---------+--------+----------------+-----------+-------+---------+-------------------+
only showing top 20 rows

Q9: When cleaning a dataset, why is it often better to handle null values before performing mathematical aggregations like sum() or avg()?

It is better to handle null values before using sum() or avg() because null values can affect the calculations and give incorrect results.

Q10: Write the code to revise a column named raw_timestamp by casting it to a TimestampType and renaming it to event_time.``

In [0]:
from pyspark.sql.functions import col
from pyspark.sql.types import TimestampType
spark_df = spark_df.withColumn("event_time", col("raw_timestamp").cast(TimestampType())).drop("raw_timestamp")
spark_df.show()

+--------------+-------+----------------+---------------+--------------------+---+------------+------+---------+--------+----------------+-----------+-------+---------+-------------------+
|transaction_id|user_id|transaction_date|       username|               email|age|subscription|region|     city|store_id|product_category|sale_amount|  price|   status|         event_time|
+--------------+-------+----------------+---------------+--------------------+---+------------+------+---------+--------+----------------+-----------+-------+---------+-------------------+
|           130|   1160|      2026-01-01|  whitneyjustin|derrickhale@examp...| 48|       Basic| South|Hyderabad|       6|     Electronics|    3399.78| 389.57|     NULL|1982-12-26 19:49:53|
|           222|   1121|      2025-08-19|     jonathan70| scott37@example.org| 42|       Basic|  East|  Chennai|      20|           Books|    2110.99|1869.75|  Pending|1993-12-14 00:30:06|
|           227|   1055|      2026-03-29|      dpeterson|martinezmichele@e...| 41|     Premium| North|Bangalore|       2|     Electronics|    4754.58|2982.99|Completed|1988-01-24 20:32:51|
|           249|   1051|      2025-10-28|    byrddeborah|maldonadotoni@exa...| 20|       Basic|  West|  Chennai|       9|     Electronics|    3217.93| 719.39|Completed|1973-03-24 00:16:21|
|           265|   1016|      2026-05-22|rodriguezdaniel| jmorgan@example.com| 58|     Premium|  West|  Chennai|       5|       Groceries|     3495.5|2024.14|  Pending|1981-08-08 11:26:57|
|           205|   1199|      2026-04-04|     torreslori|gfleming@example.net| 22|     Premium|  West|Hyderabad|      10|           Books|    2068.42|1298.06|     NULL|2015-01-29 06:36:26|
|           151|   1016|      2026-05-30|franklinkristin|mbuchanan@example...| 33|       Basic| South|   Mumbai|       9|        Clothing|    2551.65| 385.85|Completed|2005-06-12 02:07:05|
|             8|   1088|      2025-12-31|    amandasmith| cwarren@example.net| 33|       Basic| South|Hyderabad|       1|     Electronics|    3446.14|1001.47|  Pending|1978-09-25 17:31:16|
|            33|   1074|      2025-11-22|  crystalcooper|  abaker@example.com| 18|       Basic| South|    Delhi|      14|        Clothing|     3891.8|2201.29|Completed|2025-01-14 07:10:02|
|            45|   1094|      2025-11-01|      stephen95|katrinawashington...| 21|       Basic|  West|    Delhi|      11|        Clothing|     975.32|2675.03|  Pending|2015-02-04 13:41:09|
|            75|   1097|      2025-09-19|    briannapugh|romeroisaac@examp...| 45|       Basic|  West|    Delhi|      14|     Electronics|    2807.92| 359.58|Completed|2007-08-06 02:43:47|
|           123|   1045|      2026-01-27|       emiranda| wmiller@example.org| 24|     Premium| North|Hyderabad|      10|           Books|    1269.13|2973.22|  Pending|2010-12-26 22:21:31|
|           216|   1107|      2025-08-04|christinamartin|ravenward@example...| 33|     Premium| South|   Mumbai|      11|           Books|     761.15|1070.37|     NULL|2010-04-21 08:35:19|
|            31|   1187|      2026-04-26|         mary79|davidhodge@exampl...| 63|       Basic|  West|    Delhi|       2|           Books|    2771.52| 652.34|Completed|2021-03-22 19:17:55|
|            62|   1083|      2025-07-02|      johnwhite| apatton@example.com| 30|     Premium|  East|    Delhi|       5|       Groceries|    4002.73| 150.03|Completed|2003-02-22 08:46:58|
|           259|   1052|      2025-11-11|         judy63|shannon10@example...| 40|     Premium|  West|  Chennai|      20|           Books|    3889.88|1257.74|Completed|1989-08-28 08:33:00|
|           227|   1088|      2025-12-27|        shawn00| brian42@example.org| 47|     Premium| North|   Mumbai|       9|     Electronics|    4672.65|1022.31|     NULL|2023-06-08 04:56:09|
|            16|   1166|      2025-09-21|     loriwright|jameswelch@exampl...| 45|       Basic| North|    Delhi|      13|       Groceries|    3082.44|2947.32|  Pending|2014-06-09 10:56:52|
|            57|   1063|      2026-02-16|         john10| gavin74@example.net| 52|     Premium| North|   Mumbai|      20|        Clothing|    3347.12|2243.38|     NULL|2021-04-16 22:48:40|
|           107|   1139|      2026-03-18|        tracy07|fuentestina@examp...| 33|     Premium| North|    Delhi|      16|       Groceries|    1705.37|  756.7|Completed|2014-02-26 19:39:19|
+--------------+-------+----------------+---------------+--------------------+---+------------+------+---------+--------+----------------+-----------+-------+---------+-------------------+
only showing top 20 rows

Q11: Explain the "Shuffle" process that occurs during a grouping operation. Why is it considered a wide transformation?

Shuffle is the process of moving data between different partitions during operations like groupBy().

it is called a wide transformation because data is moved across different partitions before processing.

 Q12: Write a code snippet that identifies and removes rows where the email column contains null values OR the username is an empty string.

In [0]:
df = df[df["email"].notna()]
df = df[df["username"] != ""]

Q13: How do you use the .agg() function to calculate multiple statistics at once, such as the min, max, and mean of the price column?

In [0]:
df["price"].agg(["min", "max", "mean"])

min       50.130000
max     2998.800000
mean    1551.093525
Name: price, dtype: float64

Q14: In the context of cleaning a dataset, what is the risk of using inferSchema=true when your source data contains messy or inconsistent date formats?

If the date formats are different, inferSchema may not identify the correct data type. Because of this, the data may not be processed correctly and can cause errors later.