In [116]:
import pandas as pd

In [117]:
df = pd.read_csv("C:/Users/HP/OneDrive/Desktop/Projects/Week1_Assessment/combined_dataset.csv")

In [118]:
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe

In [119]:
print("Colums in Data Frame : \n ",df.columns)

Colums in Data Frame :
  Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')

In [120]:
print("No.of rows, columns in DataFrame :" ,df.shape)

No.of rows, columns in DataFrame : (1000, 24)

In [121]:
df.tail()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

In [122]:
df.dtypes

product_id                  int64
title                      object
product_description        object
rating                    float64
ratings_count               int64
initial_price               int64
discount                  float64
final_price                object
currency                   object
images                     object
delivery_options           object
product_details            object
breadcrumbs                object
product_specifications     object
amount_of_stars            object
what_customers_said        object
seller_name                object
sizes                      object
videos                     object
seller_information         object
variations                 object
best_offer                 object
more_offers                object
category                   object
dtype: object

In [123]:
df.isnull().sum()

product_id                  0
title                       0
product_description         0
rating                      0
ratings_count               0
initial_price               0
discount                  121
final_price                 0
currency                    0
images                      0
delivery_options            0
product_details             0
breadcrumbs                 0
product_specifications      0
amount_of_stars             0
what_customers_said       573
seller_name               301
sizes                       0
videos                    781
seller_information        301
variations                562
best_offer                  0
more_offers                 0
category                    0
dtype: int64

In [124]:
df["discount"] = df["discount"].fillna(0)

In [125]:
df["what_customers_said"] = df["what_customers_said"].fillna("No Review")

In [126]:
df["seller_information"] = df["seller_information"].fillna("Not Available")

In [127]:
df["variations"] = df["variations"].fillna("No Variations")

In [128]:
df['seller_name']=df['seller_name'].fillna('Unknown Seller')

In [129]:
df.drop("videos", axis=1, inplace=True)

In [130]:
print("After handling missing values\n",df.isnull().sum())

After handling missing values
 product_id                0
title                     0
product_description       0
rating                    0
ratings_count             0
initial_price             0
discount                  0
final_price               0
currency                  0
images                    0
delivery_options          0
product_details           0
breadcrumbs               0
product_specifications    0
amount_of_stars           0
what_customers_said       0
seller_name               0
sizes                     0
seller_information        0
variations                0
best_offer                0
more_offers               0
category                  0
dtype: int64

In [139]:
# Perform basic operations (filter rows, select columns)
print("Products with discount > 80")
df[df['discount'] > 80]

Products with discount > 80

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,product_specifications,amount_of_stars,what_customers_said,seller_name,sizes,seller_information,variations,best_offer,more_offers,category
18,22409156,Kastner,Women Textured Tang Slim Belt,3.8,9,1399,84.0,"""₹223.00""",INR,http://assets.myntassets.com/assets/images/224...,...,"[{""specification_name"":""Belt Width"",""specifica...","{""1_star"":2,""2_stars"":0,""3_stars"":0,""4_stars"":...",No Review,Kas███r L███her█████████Pvt██████,"[{""size"":""26"",""value"":""26.0in"",""value_name"":""T...",A-5███ADA███R V█████████ De█████████████████████,"[{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",belts
21,1728397,Mactree,Men Brown Solid Mid-Top Flat Boots,3.9,1727,9060,88.0,"""₹1,087.00""",INR,http://assets.myntassets.com/assets/images/172...,...,"[{""specification_name"":""Ankle Height"",""specifi...","{""1_star"":228,""2_stars"":89,""3_stars"":186,""4_st...",No Review,MAX███ IN███NAT██████,"[{""size"":""6"",""value"":""25.1cm"",""value_name"":""To...","21/███10 ███NS █████████4 ,███████████████████...",[{}],"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",boots
176,13382036,plusS,Women Olive Green Accordion Pleated Midi A-Lin...,4.2,623,1899,83.0,"""₹322.00""",INR,http://assets.myntassets.com/assets/images/133...,...,"[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":47,""2_stars"":31,""3_stars"":60,""4_star...","[{""percentage"":""86"",""value_name"":""Fit, Just Ri...",Shi███Int███ati█████████rel███,"[{""size"":""S"",""value"":""36.0in"",""value_name"":""Bu...",Fir███and███con█████████A 3███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
213,10125241,KARATCART,Green Gold-Plated Beaded Enamelled Floral Chan...,4.2,22,1711,82.0,"""₹307.00""",INR,http://assets.myntassets.com/assets/images/101...,...,"[{""specification_name"":""Base Metal"",""specifica...","{""1_star"":1,""2_stars"":3,""3_stars"":2,""4_stars"":...",No Review,KOK███V G███AL █████████,"[{""size"":""Onesize""}]",Sho███58-███Sec█████████ain███████████████████...,No Variations,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",earrings
227,13401002,Adwitiya Collection,Gold-Toned & Green Dome Shaped Jhumkas,0.0,0,3189,81.0,"""₹599.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"[{""specification_name"":""Base Metal"",""specifica...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No Review,ADW███YA ███HIO█████████ LI██████,"[{""size"":""Onesize""}]","D-1███ Vi███ Vi█████████, U█████████████████████",[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",earrings
228,13340876,Kord Store,Red Gold Plated Meenakari Classic Jhumkas,4.4,7,4524,88.0,"""₹542.00""",INR,http://assets.myntassets.com/assets/images/133...,...,"[{""specification_name"":""Base Metal"",""specifica...","{""1_star"":1,""2_stars"":0,""3_stars"":0,""4_stars"":...",No Review,Kor███yst███,"[{""size"":""Onesize""}]","1st███oor███apa█████████,Na███████████████████...",No Variations,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",earrings
229,12930940,TOKYO TALKIES X rubans FASHION ACCESSORIES,Gold-Plated & White Contemporary Drop Earrings,3.9,14,1650,81.0,"""₹313.00""",INR,http://assets.myntassets.com/assets/images/129...,...,"[{""specification_name"":""Base Metal"",""specifica...","{""1_star"":1,""2_stars"":3,""3_stars"":0,""4_stars"":...",No Review,Sup███om ███,"[{""size"":""Onesize""}]",Plo███o- ███ 1s█████████Sui███████████████████...,No Variations,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",earrings
236,22593680,ZENEME,Gold-Plated Dome Shaped Jhumkas Earrings,0.0,0,2999,87.0,"""₹389.00""",INR,http://assets.myntassets.com/assets/images/225...,...,"[{""specification_name"":""Base Metal"",""specifica...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No Review,GLO███ NE███,"[{""size"":""Onesize""}]",FIR███FLO███ 50█████████ND ███████████████████...,"[{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",earrings
356,19837040,High Star,Women Olive Green Solid Crop Padded Jacket,4.1,41,3749,85.0,"""₹3,749.00""",INR,http://assets.myntassets.com/assets/images/198...,...,"[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":0,""2_stars"":2,""3_stars"":7,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Unknown Seller,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Bu...",Not Available,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",jackets
357,19837008,High Star,Women Navy Blue Solid Parka Jacket,3.9,32,4549,85.0,"""₹4,549.00""",INR,http://assets.myntassets.com/assets/images/198...,...,"[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":5,""2_stars"":2,""3_stars"":2,""4_stars"":...","[{""percentage"":""57"",""value_name"":""Fit, Just Ri...",Unknown Seller,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Bu...",Not Available,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",jackets
447,12509548,Ishin,Women Maroon & Off-White Printed A-Line Kurta ...,0.0,0,3899,86.0,"""₹545.00""",INR,http://assets.myntassets.com/assets/images/125...,...,"[{""specification_name"":""Body Shape ID"",""specif...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Men███Bra███Tec█████████ Pr███████████████,"[{""size"":""S"",""value"":""36.5in"",""value_name"":""Bu...",2nd███oor███O. █████████Lan███████████████████...,No Variations,"{""applicable_on"":""Orders above Rs. 1299 (only ...","[{""offer_name"":""10% Instant Discount on Citi C...",kurtas
491,17359602,Swiss Design,Pack Of 20 Assorted 5-Ply Anti-Pollution N95 M...,3.0,2,1500,85.0,"""₹225.00""",INR,http://assets.myntassets.com/assets/images/173...,...,"[{""specification_name"":""Adjustable"",""specifica...","{""1_star"":1,""2_stars"":0,""3_stars"":0,""4_stars"":...",No Review,HOU███OF ███NDS█████████LLP███,"[{""size"":""Onesize""}]",3RD███OOR███ AN█████████OCK███████████████████...,No Variations,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",outdoor-masks
507,15294314,Zaveri Pearls,Set of 2 Rose Gold Plated CZ-Studded Contempor...,4.4,27,1995,82.0,"""₹359.00""",INR,http://assets.myntassets.com/assets/images/152...,...,"[{""specification_name"":""Base Metal"",""specifica...","{""1_star"":1,""2_stars"":0,""3_stars"":4,""4_stars"":...",No Review,ZAV███ PE███S,"[{""size"":""Onesize""}]","12,███T F███R, █████████LDG███████████████████...",No Variations,"{""applicable_on"":""Orders above Rs. 1299 (only ...","[{""offer_name"":""10% Instant Discount on Citi C...",ring
508,16254760,Zaveri Pearls,Set Of 3 Gold-Plated White & Green Kundan-Stud...,4.2,504,2250,81.0,"""₹2,250.00""",INR,http://assets.myntassets.com/assets/images/162...,...,"[{""specification_name"":""Base Metal"",""specifica...","{""1_star"":33,""2_stars"":26,""3_stars"":57,""4_star...",No Review,Unknown Seller,"[{""size"":""Onesize"",""value"":""2.5in"",""value_name...",Not Available,No Variations,{},"[{""offer_name"":""10% Instant Discount on Citi C...",ring
512,15679734,John Karsun,Men Black Comfort Sandals,2.7,10,3649,81.0,"""₹693.00""",INR,http://assets.myntassets.com/assets/images/156...,...,"[{""specification_name"":""Character"",""specificat...","{""1_star"":3,""2_stars"":3,""3_stars"":1,""4_stars"":...",No Review,KAR███ OV███EAS███,"[{""size"":""6"",""value"":""25.1cm"",""value_name"":""To...",179███Kav███ Ku█████████2Ka███████████████████...,No Variations,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",sandals
540,19823504,VAIRAGEE,Black Embellished Sequinned Celebrity Saree,4.2,19,9995,83.0,"""₹1,699.00""",INR,http://assets.myntassets.com/assets/images/198...,...,"[{""specification_name"":""Blouse"",""specification...","{""1_star"":3,""2_stars"":0,""3_stars"":1,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fabric Qual...",Viv███ In███nat██████,"[{""size"":""Onesize""}]",201███ew ███dar█████████mar███████████████████...,"[{},{},{}]","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",sarees
767,17156676,Thomas Scott,Men Green Sustainable Sweatshirt,3.6,20,4799,85.0,"""₹4,799.00""",INR,http://assets.myntassets.com/assets/images/171...,...,"[{""specification_name"":""Body or Garment Size"",...","{""1_star"":3,""2_stars"":2,""3_stars"":3,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Unknown Seller,"[{""size"":""S"",""value"":""39.0in"",""value_name"":""Ch...",Not Available,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",sweatshirts
769,17157846,Thomas Scott,Men Blue Sustainable Sweatshirt,3.5,10,3999,82.0,"""₹3,999.00""",INR,http://assets.myntassets.com/assets/images/171...,...,"[{""specification_name"":""Body or Garment Size"",...","{""1_star"":2,""2_stars"":0,""3_stars"":2,""4_stars"":...","[{""percentage"":""50"",""value_name"":""Fit, A Littl...",Unknown Seller,"[{""size"":""S"",""value"":""39.0in"",""value_name"":""Ch...",Not Available,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",sweatshirts
842,18972596,MALHAAR,White & Brown Print Smocked Cinched Waist Top,0.0,0,3329,82.0,"""₹599.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"[{""specification_name"":""Body Shape ID"",""specif...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No Review,BED███E S███IES██████,"[{""size"":""XS"",""value"":""33.0in"",""value_name"":""T...",1/4███Rii███Ind█████████rea███████████████████...,"[{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
874,17950198,PURVAJA,Women Solid Pink Round Neck Leg of Mutton Slee...,3.4,29,2199,81.0,"""₹2,199.00""",INR,http://assets.myntassets.com/assets/images/179...,...,"[{""specification_name"":""Body Shape ID"",""specif...","{""1_star"":7,""2_stars"":3,""3_stars"":3,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Loose""...",Unknown Seller,"[{""size"":""S"",""value"":""32.0in"",""value_name"":""To...",Not Available,"[{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",tops
888,17950208,PURVAJA,Pink Solid Crop Top,3.5,20,2199,81.0,"""₹2,199.00""",INR,http://assets.myntassets.com/assets/images/179...,...,"[{""specification_name"":""Body Shape ID"",""specif...","{""1_star"":3,""2_stars"":1,""3_stars"":4,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, A Litt...",Unknown Seller,"[{""size"":""S"",""value"":""32.0in"",""value_name"":""To...",Not Available,No Variations,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tops
896,17950338,PURVAJA,Women Peach-Coloured Crop Top,4.2,16,2199,81.0,"""₹2,199.00""",INR,http://assets.myntassets.com/assets/images/179...,...,"[{""specification_name"":""Body Shape ID"",""specif...","{""1_star"":0,""2_stars"":0,""3_stars"":2,""4_stars"":...",No Review,Unknown Seller,"[{""size"":""S"",""value"":""32.0in"",""value_name"":""To...",Not Available,"[{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",tops
920,18688608,Nasher Miles,Jaisalmer Textured Large Trolley Bag,3.3,8,17995,85.0,"""₹17,995.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":3,""2_stars"":0,""3_stars"":0,""4_stars"":...",No Review,Unknown Seller,"[{""size"":""S"",""value"":""55.0cm"",""value_name"":""Ba...",Not Available,"[{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",trolley-bag
925,22323008,Dennis Lingo,Men Slim Fit Chino Trousers,3.8,5,3099,82.0,"""₹557.00""",INR,http://assets.myntassets.com/assets/images/223...,...,"[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":0,""2_stars"":0,""3_stars"":2,""4_stars"":...",No Review,Men███Bra███Tec█████████ Pr███████████████,"[{""size"":""28"",""value"":""23.0in"",""value_name"":""T...",2nd███oor███O. █████████Lan███████████████████...,"[{},{},{},{},{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",trousers
976,13721540,Art Street,Set Of 3 Brown & Green Monuments Theme Framed ...,3.9,8,3500,84.0,"""₹560.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"[{""specification_name"":""Features"",""specificati...","{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...",No Review,EDG███QUA███,"[{""size"":""Onesize""}]",I-6███URA███R I█████████ AR███████████████████...,No Variations,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",wall-art
990,9053317,TIMESMITH,Men Black Analogue Watch TSC-008,3.7,304,2499,88.0,"""₹2,499.00""",INR,http://assets.myntassets.com/assets/images/905...,...,"[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":54,""2_stars"":20,""3_stars"":34,""4_star...",No Review,Unknown Seller,"[{""size"":""Onesize""}]",Not Available,No Variations,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches

In [140]:
print("Products with rating > 4")
df[df["rating"] > 4]

Products with rating > 4

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,product_specifications,amount_of_stars,what_customers_said,seller_name,sizes,seller_information,variations,best_offer,more_offers,category
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",No Review,Unknown Seller,"[{""size"":""Onesize""}]",Not Available,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",No Review,Unknown Seller,"[{""size"":""S""}]",Not Available,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"[{""specification_name"":""Compartment Closure"",""...","{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",No Review,Unknown Seller,"[{""size"":""Onesize""}]",Not Available,No Variations,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"[{""specification_name"":""Body or Garment Size"",...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No Review,Unknown Seller,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",Not Available,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe
5,17198778,H&M,Beige & Tan Solid Stoneware Soap Dispenser,4.5,42,1399,0.0,"""₹1,399.00""",INR,http://assets.myntassets.com/assets/images/171...,...,"[{""specification_name"":""Finish"",""specification...","{""1_star"":2,""2_stars"":2,""3_stars"":0,""4_stars"":...",No Review,H &███Hen███ & █████████eta█████████████████████,"[{""size"":""Onesize""}]",Pra███yat███fra█████████PVT███████████████████...,"[{},{}]","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",bathroom-accessories
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
991,2466414,Daniel Klein,Women Brown Analogue Watch DK11467-6,4.4,940,6950,53.0,"""₹3,266.00""",INR,http://assets.myntassets.com/assets/images/246...,...,"[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":56,""2_stars"":21,""3_stars"":42,""4_star...",No Review,DES███ER ███GRE█████████IA ██████,"[{""size"":""Onesize""}]","Fir███Flo███ Pl█████████, I███████████████████...",No Variations,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
992,11791782,CASIO,Youth Digital Women Red Digital Watch I117 DW-...,4.6,29,3595,10.0,"""₹3,235.00""",INR,http://assets.myntassets.com/assets/images/117...,...,"[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...",No Review,Fla███ech███tai███,"[{""size"":""Onesize""}]","3rd███165███th █████████, s███████████████████...",No Variations,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
994,8481603,French Connection,Women Silver-Toned Analogue Watch FCN0001B,4.5,149,6250,70.0,"""₹6,250.00""",INR,http://assets.myntassets.com/assets/images/848...,...,"[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":7,""2_stars"":1,""3_stars"":8,""4_stars"":...",No Review,Unknown Seller,"[{""size"":""Onesize""}]",Not Available,No Variations,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No Review,Unknown Seller,"[{""size"":""Onesize""}]",Not Available,No Variations,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",No Review,Tru███m R███il,"[{""size"":""Onesize""}]",Sho███o. ███-10█████████enu███████████████████...,No Variations,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches

In [143]:
df1=df[['product_id','title','category','initial_price','discount','final_price']]
print(df1)

     product_id           title   category  initial_price  discount  \
0       8376765     Lino Perros  backpacks           3995      58.0
1       9136281  Tommy Hilfiger  backpacks           2899      35.0
2      17633752           Lavie  backpacks           2999      65.0
3       1376949          F Gear  backpacks           1675      52.0
4      13939916       MYTRIDENT  bath-robe           2899      17.0
..          ...             ...        ...            ...       ...
995    13698258           KREDO    watches          11890      50.0
996    16896006           GUESS    watches           8900      45.0
997     1708108        GIORDANO    watches           7950      50.0
998    19280114        Fastrack    watches           3295      20.0
999    18601682         BOLDFIT  yoga-mats            699      31.0

      final_price
0     "₹3,995.00"
1     "₹2,899.00"
2     "₹2,999.00"
3     "₹1,675.00"
4     "₹2,899.00"
..            ...
995  "₹11,890.00"
996   "₹8,900.00"
997   "₹7,950.00"
998   "₹2,636.00"
999     "₹699.00"

[1000 rows x 6 columns]

In [150]:
# Remove duplicates
df = df.drop_duplicates()

In [148]:
df.shape

(1000, 23)

In [ ]:
#.Create a derived column (total_amount = price * quantity)

In [151]:
df["total_amount"] = df["final_price"] * 1 # cause quantity column is not present in the dataset

In [152]:
df

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,seller_information,variations,best_offer,more_offers,category,total_amount
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",No Review,Unknown Seller,"[{""size"":""Onesize""}]",Not Available,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,"""₹3,995.00"""
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",No Review,Unknown Seller,"[{""size"":""Onesize""}]",Not Available,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,"""₹2,899.00"""
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",No Review,Unknown Seller,"[{""size"":""S""}]",Not Available,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,"""₹2,999.00"""
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",No Review,Unknown Seller,"[{""size"":""Onesize""}]",Not Available,No Variations,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,"""₹1,675.00"""
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No Review,Unknown Seller,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",Not Available,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe,"""₹2,899.00"""
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",No Review,Unknown Seller,"[{""size"":""Onesize""}]",Not Available,No Variations,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches,"""₹11,890.00"""
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No Review,Unknown Seller,"[{""size"":""Onesize""}]",Not Available,No Variations,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches,"""₹8,900.00"""
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",No Review,Unknown Seller,"[{""size"":""Onesize""}]",Not Available,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches,"""₹7,950.00"""
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",No Review,Tru███m R███il,"[{""size"":""Onesize""}]",Sho███o. ███-10█████████enu███████████████████...,No Variations,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches,"""₹2,636.00"""
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",No Review,Unknown Seller,"[{""size"":""Medium""}]",Not Available,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats,"""₹699.00"""

In [153]:
df.to_csv('Cleaned_Combined_dataset.csv', index=False)